# rprogramming3
setwd("C:\\Users\\lenovo\\Desktop\\Rlearning\\r programming\\week4")
# install.packages("swirl")
library(swirl)
swirl()
install_from_swirl("R Programming")
# sessionInfo()
library(UsingR)
outcome <- read.csv("outcome-of-care-measures.csv", colClasses = "character")
head(outcome)
str(outcome)
ncol(outcome) 
outcome[, 11] <- as.numeric(outcome[, 11])
## You may get a warning about NAs being introduced; that is okay
hist(outcome[, 11])
head(outcome[, 11])
names(outcome)
source("submitscript3.R")
